services:
  #PHP Service
  tenis_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenis_php
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - app-network


  #Nginx Service
  tenis_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: tenis_nginx
    tty: true
    ports:
      - ${API_PORT}:80
      - "4443:443"
    networks:
      - app-network
    volumes: 
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  tenis_bd:
    image: mysql:8.0
    container_name: tenis_bd
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: example_database
    networks:
      - app-network
    volumes:
      - database:/var/lib/mysql

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  database:
    driver: local